### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AAndromedAA** [AAndromedAA/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by Marsichek** [comment]
Hey! I`m Elon Musk and I`m the Technoking of Tesla and the Emperor of Mars. I like rockets and space, also want to be the first human on Mars. I`m very cheerful guy and sometimes can use drugs during interviews (remember, drugs are bad. Don`t use them if you are not the Caesar of Space as me ^_^). Follow me and let`s conquer new planets!

**Comment by AAndromedAA** [comment]
Cool!
