### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by AAndromedAA** [AAndromedAA/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by Marsichek** [comment]
Twitter: https://twitter.com/elonmusk
Facebook: https://www.facebook.com/Elon-Musk-19958149870/
Instagram: https://www.instagram.com/elonmusk/?hl=en
Tesla website: http://ir.tesla.com/contact-us
